POST http://localhost:5000/app/signup
Content-Type: application/json

{
    "fullName":"joseph",
    "lastName":"Patel",
    "phone":  9099921883,
    "email": "joey@gmail.com",
    "roll":21,
    "password":"josejosey"
}
